package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Artikelsolr generated by hbm2java
 */
@Entity
@Table(name = "Artikelsolr", catalog = "sitescrawler_dev_db")
public class Artikelsolr implements java.io.Serializable
{

    private ArtikelsolrId id;
    private Archiveintrag archiveintrag;

    public Artikelsolr()
    {
    }

    public Artikelsolr(ArtikelsolrId id, Archiveintrag archiveintrag)
    {
        this.id = id;
        this.archiveintrag = archiveintrag;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "solrid", column = @Column(name = "solrid", nullable = false)),
                          @AttributeOverride(name = "archiveintragArchiveintragid",
                                             column = @Column(name = "Archiveintrag_archiveintragid", nullable = false)) })
    public ArtikelsolrId getId()
    {
        return this.id;
    }

    public void setId(ArtikelsolrId id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Archiveintrag_archiveintragid", nullable = false, insertable = false, updatable = false)
    public Archiveintrag getArchiveintrag()
    {
        return this.archiveintrag;
    }

    public void setArchiveintrag(Archiveintrag archiveintrag)
    {
        this.archiveintrag = archiveintrag;
    }

}
