package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArtikelsolrId generated by hbm2java
 */
@Embeddable
public class ArtikelsolrId implements java.io.Serializable
{

    private int solrid;
    private int archiveintragArchiveintragid;

    public ArtikelsolrId()
    {
    }

    public ArtikelsolrId(int solrid, int archiveintragArchiveintragid)
    {
        this.solrid = solrid;
        this.archiveintragArchiveintragid = archiveintragArchiveintragid;
    }

    @Column(name = "solrid", nullable = false)
    public int getSolrid()
    {
        return this.solrid;
    }

    public void setSolrid(int solrid)
    {
        this.solrid = solrid;
    }

    @Column(name = "Archiveintrag_archiveintragid", nullable = false)
    public int getArchiveintragArchiveintragid()
    {
        return this.archiveintragArchiveintragid;
    }

    public void setArchiveintragArchiveintragid(int archiveintragArchiveintragid)
    {
        this.archiveintragArchiveintragid = archiveintragArchiveintragid;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ArtikelsolrId))
            return false;
        ArtikelsolrId castOther = (ArtikelsolrId) other;

        return (this.getSolrid() == castOther.getSolrid()) && (this.getArchiveintragArchiveintragid() == castOther.getArchiveintragArchiveintragid());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getSolrid();
        result = 37 * result + this.getArchiveintragArchiveintragid();
        return result;
    }

}
