package de.sitescrawler.jpa;
// Generated 02.05.2017 16:40:27 by Hibernate Tools 5.2.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Artikelsolr generated by hbm2java
 */
@Entity
@XmlRootElement(name="artikel")
public class Artikel implements java.io.Serializable
{
    private static final long  serialVersionUID = 1L;
    private Set<Archiveintrag> archiveintraege  = new HashSet<>(0);
    private String             solrid;

    private Date               erstellungsdatum;
    private String             autor;
    private String             titel;
    private String             beschreibung;
    private String             link;
    private List<String>       absaetzeArtikel  = new ArrayList();

    public Artikel()
    {
    }

    public Artikel(Set<Archiveintrag> archiveintraege, String solrid)
    {
        this.archiveintraege = archiveintraege;
        this.solrid = solrid;
    }

    public Artikel(Date erstellungsdatum, String autor, String titel, String beschreibung, String link)
    {
        super();
        this.erstellungsdatum = erstellungsdatum;
        this.autor = autor;
        this.titel = titel;
        this.beschreibung = beschreibung;
        this.link = link;
    }

    public Artikel(Date erstellungsdatum, String autor, String titel, String beschreibung, String link, List<String> absaetzeArtikel)
    {
        super();
        this.erstellungsdatum = erstellungsdatum;
        this.autor = autor;
        this.titel = titel;
        this.beschreibung = beschreibung;
        this.link = link;
        this.absaetzeArtikel = absaetzeArtikel;
    }

    public Artikel(Set<Archiveintrag> archiveintraege, String solrid, Date erstellungsdatum, String autor, String titel, String beschreibung, String link,
                   List<String> absaetzeArtikel)
    {
        this.archiveintraege = archiveintraege;
        this.solrid = solrid;
        this.erstellungsdatum = erstellungsdatum;
        this.autor = autor;
        this.titel = titel;
        this.beschreibung = beschreibung;
        this.link = link;
        this.absaetzeArtikel = absaetzeArtikel;
    }

    @ManyToMany(fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH })
    @JoinTable(name = "Archiveintrag_beinhaltet_Artikel", joinColumns = { @JoinColumn(name = "Artikel_solrid", nullable = false, updatable = false) },
    inverseJoinColumns = { @JoinColumn(name = "Archiveintrag_archiveintragid", nullable = false, updatable = false) })
    @XmlTransient
    public Set<Archiveintrag> getArchiveintraege()
    {
        return this.archiveintraege;
    }

    public void setArchiveintraege(Set<Archiveintrag> archiveintraege)
    {
        this.archiveintraege = archiveintraege;
    }

    @Id

    @Column(name = "solrid", unique = true, nullable = false)
    public String getSolrid()
    {
        return this.solrid;
    }

    public void setSolrid(String solrid)
    {
        this.solrid = solrid;
    }

    @XmlElement(name="datum")
    public Date getErstellungsdatum()
    {
        return this.erstellungsdatum;
    }

    public void setErstellungsdatum(Date erstellungsdatum)
    {
        this.erstellungsdatum = erstellungsdatum;
    }

    @XmlElement(name="autor")
    public String getAutor()
    {
        return this.autor;
    }

    public void setAutor(String autor)
    {
        this.autor = autor;
    }

    @XmlElement(name="titel")
    public String getTitel()
    {
        return this.titel;
    }

    public void setTitel(String titel)
    {
        this.titel = titel;
    }

    @XmlElement(name="beschreibung")
    public String getBeschreibung()
    {
        return this.beschreibung;
    }

    public void setBeschreibung(String beschreibung)
    {
        this.beschreibung = beschreibung;
    }

    @XmlElement(name="link")
    public String getLink()
    {
        return this.link;
    }

    public void setLink(String link)
    {
        this.link = link;
    }

    @Transient
    public List<String> getAbsaetzeArtikel()
    {
        return this.absaetzeArtikel;
    }

    public void setAbsaetzeArtikel(List<String> absaetzeArtikel)
    {
        this.absaetzeArtikel = absaetzeArtikel;
    }

}
