package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filtermanager generated by hbm2java
 */
@Entity
@Table(name = "Filtermanager", catalog = "sitescrawler_dev_db")
public class Filtermanager implements java.io.Serializable
{

    private String                  identifikation;
    private int                     maxfiltergruppen;
    private Set<Filterprofil>       filterprofile       = new HashSet<>(0);
    private Set<Filterprofilgruppe> filterprofilgruppen = new HashSet<>(0);

    public Filtermanager()
    {
    }

    public Filtermanager(String identifikation, int maxfiltergruppen)
    {
        this.identifikation = identifikation;
        this.maxfiltergruppen = maxfiltergruppen;
    }

    public Filtermanager(String identifikation, int maxfiltergruppen, Set<Filterprofil> filterprofile, Set<Filterprofilgruppe> filterprofilgruppen)
    {
        this.identifikation = identifikation;
        this.maxfiltergruppen = maxfiltergruppen;
        this.filterprofile = filterprofile;
        this.filterprofilgruppen = filterprofilgruppen;
    }

    @Id

    @Column(name = "identifikation", unique = true, nullable = false, length = 45)
    public String getIdentifikation()
    {
        return this.identifikation;
    }

    public void setIdentifikation(String identifikation)
    {
        this.identifikation = identifikation;
    }

    @Column(name = "maxfiltergruppe", nullable = false)
    public int getMaxfiltergruppe()
    {
        return this.maxfiltergruppen;
    }

    public void setMaxfiltergruppe(int maxfiltergruppen)
    {
        this.maxfiltergruppen = maxfiltergruppen;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "filtermanager")
    public Set<Filterprofil> getFilterprofile()
    {
        return this.filterprofile;
    }

    public void setFilterprofile(Set<Filterprofil> filterprofile)
    {
        this.filterprofile = filterprofile;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "filtermanager")
    public Set<Filterprofilgruppe> getFilterprofilgruppen()
    {
        return this.filterprofilgruppen;
    }

    public void setFilterprofilgruppen(Set<Filterprofilgruppe> filterprofilgruppen)
    {
        this.filterprofilgruppen = filterprofilgruppen;
    }

}
