package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FilterprofilgruppeId generated by hbm2java
 */
@Embeddable
public class FilterprofilgruppeId implements java.io.Serializable
{

    private String titel;
    private String filtermanagerIdentifikation;

    public FilterprofilgruppeId()
    {
    }

    public FilterprofilgruppeId(String titel, String filtermanagerIdentifikation)
    {
        this.titel = titel;
        this.filtermanagerIdentifikation = filtermanagerIdentifikation;
    }

    @Column(name = "titel", nullable = false)
    public String getTitel()
    {
        return this.titel;
    }

    public void setTitel(String titel)
    {
        this.titel = titel;
    }

    @Column(name = "Filtermanager_identifikation", nullable = false, length = 45)
    public String getFiltermanagerIdentifikation()
    {
        return this.filtermanagerIdentifikation;
    }

    public void setFiltermanagerIdentifikation(String filtermanagerIdentifikation)
    {
        this.filtermanagerIdentifikation = filtermanagerIdentifikation;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof FilterprofilgruppeId))
            return false;
        FilterprofilgruppeId castOther = (FilterprofilgruppeId) other;

        return ((this.getTitel() == castOther.getTitel())
                || (this.getTitel() != null && castOther.getTitel() != null && this.getTitel().equals(castOther.getTitel())))
               && ((this.getFiltermanagerIdentifikation() == castOther.getFiltermanagerIdentifikation())
                   || (this.getFiltermanagerIdentifikation() != null && castOther.getFiltermanagerIdentifikation() != null
                       && this.getFiltermanagerIdentifikation().equals(castOther.getFiltermanagerIdentifikation())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (getTitel() == null ? 0 : this.getTitel().hashCode());
        result = 37 * result + (getFiltermanagerIdentifikation() == null ? 0 : this.getFiltermanagerIdentifikation().hashCode());
        return result;
    }

}
