package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FilterprofilId generated by hbm2java
 */
@Embeddable
public class FilterprofilId implements java.io.Serializable
{

    private String filtermanagerIdentifikation;
    private String filterprofilname;

    public FilterprofilId()
    {
    }

    public FilterprofilId(String filtermanagerIdentifikation, String filterprofilname)
    {
        this.filtermanagerIdentifikation = filtermanagerIdentifikation;
        this.filterprofilname = filterprofilname;
    }

    @Column(name = "Filtermanager_identifikation", nullable = false, length = 45)
    public String getFiltermanagerIdentifikation()
    {
        return this.filtermanagerIdentifikation;
    }

    public void setFiltermanagerIdentifikation(String filtermanagerIdentifikation)
    {
        this.filtermanagerIdentifikation = filtermanagerIdentifikation;
    }

    @Column(name = "filterprofilname", nullable = false)
    public String getFilterprofilname()
    {
        return this.filterprofilname;
    }

    public void setFilterprofilname(String filterprofilname)
    {
        this.filterprofilname = filterprofilname;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof FilterprofilId))
            return false;
        FilterprofilId castOther = (FilterprofilId) other;

        return ((this.getFiltermanagerIdentifikation() == castOther.getFiltermanagerIdentifikation())
                || (this.getFiltermanagerIdentifikation() != null && castOther.getFiltermanagerIdentifikation() != null
                    && this.getFiltermanagerIdentifikation().equals(castOther.getFiltermanagerIdentifikation())))
               && ((this.getFilterprofilname() == castOther.getFilterprofilname())
                   || (this.getFilterprofilname() != null && castOther.getFilterprofilname() != null
                       && this.getFilterprofilname().equals(castOther.getFilterprofilname())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (getFiltermanagerIdentifikation() == null ? 0 : this.getFiltermanagerIdentifikation().hashCode());
        result = 37 * result + (getFilterprofilname() == null ? 0 : this.getFilterprofilname().hashCode());
        return result;
    }

}
