package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Firma generated by hbm2java
 */
@Entity
@Table(name = "Firma", catalog = "sitescrawler_dev_db")
public class Firma extends Filtermanager implements java.io.Serializable
{

    private Set<Mitarbeiter> mitarbeiter = new HashSet<>(0);

    public Firma()
    {
    }

    public Firma(Set<Mitarbeiter> mitarbeiter)
    {
        this.mitarbeiter = mitarbeiter;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "firma")
    public Set<Mitarbeiter> getMitarbeiter()
    {
        return this.mitarbeiter;
    }

    public void setMitarbeiter(Set<Mitarbeiter> mitarbeiter)
    {
        this.mitarbeiter = mitarbeiter;
    }

}
