package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Firmenrolle generated by hbm2java
 */
@Entity
@Table(name = "Firmenrolle", catalog = "sitescrawler_dev_db")
public class Firmenrolle implements java.io.Serializable
{

    private String           firmenrolle;
    private Set<Mitarbeiter> mitarbeiter = new HashSet<Mitarbeiter>(0);

    public Firmenrolle()
    {
    }

    public Firmenrolle(String firmenrolle)
    {
        this.firmenrolle = firmenrolle;
    }

    public Firmenrolle(String firmenrolle, Set<Mitarbeiter> mitarbeiter)
    {
        this.firmenrolle = firmenrolle;
        this.mitarbeiter = mitarbeiter;
    }

    @Id

    @Column(name = "firmenrolle", unique = true, nullable = false, length = 45)
    public String getFirmenrolle()
    {
        return this.firmenrolle;
    }

    public void setFirmenrolle(String firmenrolle)
    {
        this.firmenrolle = firmenrolle;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "firmenrolle")
    public Set<Mitarbeiter> getMitarbeiter()
    {
        return this.mitarbeiter;
    }

    public void setMitarbeiter(Set<Mitarbeiter> mitarbeiter)
    {
        this.mitarbeiter = mitarbeiter;
    }

}
