package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Intervall generated by hbm2java
 */
@Entity
@Table(name = "Intervall", catalog = "sitescrawler_dev_db")
public class Intervall implements java.io.Serializable
{

    private String                  intervall;

    public Intervall()
    {
    }

    public Intervall(String intervall)
    {
        this.intervall = intervall;
    }


    @Id

    @Column(name = "intervall", unique = true, nullable = false)
    public String getIntervall()
    {
        return this.intervall;
    }

    public void setIntervall(String intervall)
    {
        this.intervall = intervall;
    }

}
