package de.sitescrawler.jpa;
// Generated 02.05.2017 16:40:27 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;

import de.sitescrawler.model.ZeitIntervall;

/**
 * Intervall generated by hbm2java
 */
@Entity
public class Intervall implements java.io.Serializable
{

    private static final long serialVersionUID = 1L;
    private ZeitIntervall     zeitintervall;

    public Intervall()
    {
    }

    public Intervall(ZeitIntervall intervall)
    {
        this.zeitintervall = intervall;
    }

    @Id

    @Column(name = "intervall", unique = true, nullable = false)
    @Enumerated(EnumType.STRING)
    public ZeitIntervall getZeitIntervall()
    {
        return this.zeitintervall;
    }

    public void setZeitIntervall(ZeitIntervall intervall)
    {
        this.zeitintervall = intervall;
    }

}
