package de.sitescrawler.jpa;
// Generated 02.05.2017 16:40:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

import de.sitescrawler.model.ProfilKategorie;

/**
 * Kategorie generated by hbm2java
 */
@Entity
public class Kategorie implements java.io.Serializable
{

    private static final long serialVersionUID = 1L;
    private ProfilKategorie   kategorienname;
    private Set<Filterprofil> filterprofile    = new HashSet<>(0);

    public Kategorie()
    {
    }

    public Kategorie(ProfilKategorie kategorienname)
    {
        this.kategorienname = kategorienname;
    }

    public Kategorie(ProfilKategorie kategorienname, Set<Filterprofil> filterprofile)
    {
        this.kategorienname = kategorienname;
        this.filterprofile = filterprofile;
    }

    @Id
    @Enumerated(EnumType.STRING)
    @Column(name = "kategorienname", unique = true, nullable = false)
    public ProfilKategorie getKategorienname()
    {
        return this.kategorienname;
    }

    public void setKategorienname(ProfilKategorie kategorienname)
    {
        this.kategorienname = kategorienname;
    }

    @ManyToMany(fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH })
    @JoinTable(name = "Filterprofil_beinhaltet_Kategorie",
               joinColumns = { @JoinColumn(name = "Kategorie_kategorienname", nullable = false, updatable = false) },
               inverseJoinColumns = { @JoinColumn(name = "Filterprofil_FilterprofilId", nullable = false, updatable = false) })
    public Set<Filterprofil> getFilterprofile()
    {
        return this.filterprofile;
    }

    public void setFilterprofile(Set<Filterprofil> filterprofile)
    {
        this.filterprofile = filterprofile;
    }

}
