package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

/**
 * Kategorie generated by hbm2java
 */
@Entity
@Table(name = "Kategorie", catalog = "sitescrawler_dev_db")
public class Kategorie implements java.io.Serializable
{


    private static final long serialVersionUID = 1L;
    private String            kategorienname;


    public Kategorie()
    {
    }

    public Kategorie(String kategorienname)
    {
        this.kategorienname = kategorienname;
    }


    @Id

    @Column(name = "kategorienname", unique = true, nullable = false)
    public String getKategorienname()
    {
        return this.kategorienname;
    }

    public void setKategorienname(String kategorienname)
    {
        this.kategorienname = kategorienname;
    }

}

