package de.sitescrawler.jpa;
// Generated 02.05.2017 16:40:27 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MitarbeiterId generated by hbm2java
 */
@Embeddable
public class MitarbeiterId implements java.io.Serializable
{

    private static final long serialVersionUID = 1L;
    private String            nutzerFiltermanagerIdentifikation;
    private String            firmaFiltermanagerIdentifikation;

    public MitarbeiterId()
    {
    }

    public MitarbeiterId(String nutzerFiltermanagerIdentifikation, String firmaFiltermanagerIdentifikation)
    {
        this.nutzerFiltermanagerIdentifikation = nutzerFiltermanagerIdentifikation;
        this.firmaFiltermanagerIdentifikation = firmaFiltermanagerIdentifikation;
    }

    @Column(name = "Nutzer_Filtermanager_identifikation", nullable = false, length = 45)
    public String getNutzerFiltermanagerIdentifikation()
    {
        return this.nutzerFiltermanagerIdentifikation;
    }

    public void setNutzerFiltermanagerIdentifikation(String nutzerFiltermanagerIdentifikation)
    {
        this.nutzerFiltermanagerIdentifikation = nutzerFiltermanagerIdentifikation;
    }

    @Column(name = "Firma_Filtermanager_identifikation", nullable = false, length = 45)
    public String getFirmaFiltermanagerIdentifikation()
    {
        return this.firmaFiltermanagerIdentifikation;
    }

    public void setFirmaFiltermanagerIdentifikation(String firmaFiltermanagerIdentifikation)
    {
        this.firmaFiltermanagerIdentifikation = firmaFiltermanagerIdentifikation;
    }

    @Override
    public boolean equals(Object other)
    {
        if ((this == other))
        {
            return true;
        }
        if ((other == null))
        {
            return false;
        }
        if (!(other instanceof MitarbeiterId))
        {
            return false;
        }
        MitarbeiterId castOther = (MitarbeiterId) other;

        return ((this.getNutzerFiltermanagerIdentifikation() == castOther.getNutzerFiltermanagerIdentifikation())
                || (this.getNutzerFiltermanagerIdentifikation() != null && castOther.getNutzerFiltermanagerIdentifikation() != null
                    && this.getNutzerFiltermanagerIdentifikation().equals(castOther.getNutzerFiltermanagerIdentifikation())))
               && ((this.getFirmaFiltermanagerIdentifikation() == castOther.getFirmaFiltermanagerIdentifikation())
                   || (this.getFirmaFiltermanagerIdentifikation() != null && castOther.getFirmaFiltermanagerIdentifikation() != null
                       && this.getFirmaFiltermanagerIdentifikation().equals(castOther.getFirmaFiltermanagerIdentifikation())));
    }

    @Override
    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (this.getNutzerFiltermanagerIdentifikation() == null ? 0 : this.getNutzerFiltermanagerIdentifikation().hashCode());
        result = 37 * result + (this.getFirmaFiltermanagerIdentifikation() == null ? 0 : this.getFirmaFiltermanagerIdentifikation().hashCode());
        return result;
    }

}
