package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MitarbeiterId generated by hbm2java
 */
@Embeddable
public class MitarbeiterId implements java.io.Serializable
{

    private String firmenrolleFirmenrolle;
    private String nutzerFiltermanagerIdentifikation;
    private String firmaFiltermanagerIdentifikation;

    public MitarbeiterId()
    {
    }

    public MitarbeiterId(String firmenrolleFirmenrolle, String nutzerFiltermanagerIdentifikation, String firmaFiltermanagerIdentifikation)
    {
        this.firmenrolleFirmenrolle = firmenrolleFirmenrolle;
        this.nutzerFiltermanagerIdentifikation = nutzerFiltermanagerIdentifikation;
        this.firmaFiltermanagerIdentifikation = firmaFiltermanagerIdentifikation;
    }

    @Column(name = "Firmenrolle_firmenrolle", nullable = false, length = 45)
    public String getFirmenrolleFirmenrolle()
    {
        return this.firmenrolleFirmenrolle;
    }

    public void setFirmenrolleFirmenrolle(String firmenrolleFirmenrolle)
    {
        this.firmenrolleFirmenrolle = firmenrolleFirmenrolle;
    }

    @Column(name = "Nutzer_Filtermanager_identifikation", nullable = false, length = 45)
    public String getNutzerFiltermanagerIdentifikation()
    {
        return this.nutzerFiltermanagerIdentifikation;
    }

    public void setNutzerFiltermanagerIdentifikation(String nutzerFiltermanagerIdentifikation)
    {
        this.nutzerFiltermanagerIdentifikation = nutzerFiltermanagerIdentifikation;
    }

    @Column(name = "Firma_Filtermanager_identifikation", nullable = false, length = 45)
    public String getFirmaFiltermanagerIdentifikation()
    {
        return this.firmaFiltermanagerIdentifikation;
    }

    public void setFirmaFiltermanagerIdentifikation(String firmaFiltermanagerIdentifikation)
    {
        this.firmaFiltermanagerIdentifikation = firmaFiltermanagerIdentifikation;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof MitarbeiterId))
            return false;
        MitarbeiterId castOther = (MitarbeiterId) other;

        return ((this.getFirmenrolleFirmenrolle() == castOther.getFirmenrolleFirmenrolle())
                || (this.getFirmenrolleFirmenrolle() != null && castOther.getFirmenrolleFirmenrolle() != null
                    && this.getFirmenrolleFirmenrolle().equals(castOther.getFirmenrolleFirmenrolle())))
               && ((this.getNutzerFiltermanagerIdentifikation() == castOther.getNutzerFiltermanagerIdentifikation())
                   || (this.getNutzerFiltermanagerIdentifikation() != null && castOther.getNutzerFiltermanagerIdentifikation() != null
                       && this.getNutzerFiltermanagerIdentifikation().equals(castOther.getNutzerFiltermanagerIdentifikation())))
               && ((this.getFirmaFiltermanagerIdentifikation() == castOther.getFirmaFiltermanagerIdentifikation())
                   || (this.getFirmaFiltermanagerIdentifikation() != null && castOther.getFirmaFiltermanagerIdentifikation() != null
                       && this.getFirmaFiltermanagerIdentifikation().equals(castOther.getFirmaFiltermanagerIdentifikation())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (getFirmenrolleFirmenrolle() == null ? 0 : this.getFirmenrolleFirmenrolle().hashCode());
        result = 37 * result + (getNutzerFiltermanagerIdentifikation() == null ? 0 : this.getNutzerFiltermanagerIdentifikation().hashCode());
        result = 37 * result + (getFirmaFiltermanagerIdentifikation() == null ? 0 : this.getFirmaFiltermanagerIdentifikation().hashCode());
        return result;
    }

}
