package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Quelle generated by hbm2java
 */
@Entity
@Table(name = "Quelle", catalog = "sitescrawler_dev_db")
public class Quelle implements java.io.Serializable
{

    private Integer           qid;
    private String            name;
    private byte[]            bild;
    private String            rsslink;
    private String			  tagOderId; //TODO:DB

    public Quelle()
    {
    }

    public Quelle(String name, String rsslink)
    {
        this.name = name;
        this.rsslink = rsslink;
    }

    public Quelle(String name, byte[] bild, String rsslink)
    {
        this.name = name;
        this.bild = bild;
        this.rsslink = rsslink;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "qid", unique = true, nullable = false)
    public Integer getQid()
    {
        return this.qid;
    }

    public void setQid(Integer qid)
    {
        this.qid = qid;
    }

    @Column(name = "name", nullable = false)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "bild")
    public byte[] getBild()
    {
        return this.bild;
    }

    public void setBild(byte[] bild)
    {
        this.bild = bild;
    }

    @Column(name = "rsslink", nullable = false)
    public String getRsslink()
    {
        return this.rsslink;
    }

    public void setRsslink(String rsslink)
    {
        this.rsslink = rsslink;
    }

	public String getTagOderId() {
		return tagOderId;
	}

	public void setTagOderId(String tagOderId) {
		this.tagOderId = tagOderId;
	}


}
