package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Rolle generated by hbm2java
 */
@Entity
@Table(name = "Rolle", catalog = "sitescrawler_dev_db")
public class Rolle implements java.io.Serializable
{

    private String      rolle;
    private Set<Nutzer> nutzer = new HashSet<Nutzer>(0);

    public Rolle()
    {
    }

    public Rolle(String rolle)
    {
        this.rolle = rolle;
    }

    public Rolle(String rolle, Set<Nutzer> nutzer)
    {
        this.rolle = rolle;
        this.nutzer = nutzer;
    }

    @Id

    @Column(name = "rolle", unique = true, nullable = false, length = 45)
    public String getRolle()
    {
        return this.rolle;
    }

    public void setRolle(String rolle)
    {
        this.rolle = rolle;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "Nutzer_hat_Rolle", catalog = "sitescrawler_dev_db",
               joinColumns = { @JoinColumn(name = "Rolle_rolle", nullable = false, updatable = false) },
               inverseJoinColumns = { @JoinColumn(name = "Nutzer_Filtermanager_identifikation", nullable = false, updatable = false) })
    public Set<Nutzer> getNutzer()
    {
        return this.nutzer;
    }

    public void setNutzer(Set<Nutzer> nutzer)
    {
        this.nutzer = nutzer;
    }

}
