package de.sitescrawler.jpa;
// Generated 02.05.2017 16:40:27 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Uhrzeit generated by hbm2java
 */
@Entity
public class Uhrzeit implements java.io.Serializable
{

    private static final long       serialVersionUID    = 1L;
    private Date                    uhrzeit;
    private Set<Filterprofilgruppe> filterprofilgruppen = new HashSet<>(0);

    public Uhrzeit()
    {
    }

    public Uhrzeit(Date uhrzeit)
    {
        this.uhrzeit = uhrzeit;
    }

    public Uhrzeit(Date uhrzeit, Set<Filterprofilgruppe> filterprofilgruppen)
    {
        this.uhrzeit = uhrzeit;
        this.filterprofilgruppen = filterprofilgruppen;
    }

    @Id

    @Temporal(TemporalType.TIME)
    @Column(name = "uhrzeit", unique = true, nullable = false, length = 8)
    public Date getUhrzeit()
    {
        return this.uhrzeit;
    }

    public void setUhrzeit(Date uhrzeit)
    {
        this.uhrzeit = uhrzeit;
    }

    @ManyToMany(fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH })
    @JoinTable(name = "Filtergruppe_erstellt_zu_Uhrzeit", joinColumns = { @JoinColumn(name = "Uhrzeit_uhrzeit", nullable = false, updatable = false) },
               inverseJoinColumns = { @JoinColumn(name = "Filtergruppe_FilterprofilgruppeId", nullable = false, updatable = false) })
    public Set<Filterprofilgruppe> getFilterprofilgruppen()
    {
        return this.filterprofilgruppen;
    }

    public void setFilterprofilgruppen(Set<Filterprofilgruppe> filterprofilgruppen)
    {
        this.filterprofilgruppen = filterprofilgruppen;
    }

}
