package de.sitescrawler.jpa;
// Generated 26.04.2017 10:42:02 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Uhrzeit generated by hbm2java
 */
@Entity
@Table(name = "Uhrzeit", catalog = "sitescrawler_dev_db")
public class Uhrzeit implements java.io.Serializable
{


    private static final long serialVersionUID = 1L;
    private Date                    uhrzeit;

    public Uhrzeit()
    {
    }

    public Uhrzeit(Date uhrzeit)
    {
        this.uhrzeit = uhrzeit;
    }

    @Id

    @Temporal(TemporalType.TIME)
    @Column(name = "uhrzeit", unique = true, nullable = false, length = 8)
    public Date getUhrzeit()
    {
        return this.uhrzeit;
    }

    public void setUhrzeit(Date uhrzeit)
    {
        this.uhrzeit = uhrzeit;
    }

}
